#ifndef OPCODES_H
#define OPCODES_H

#include "numbers.h"

enum class Opcodes : Byte {
	BRK = 0x00,
	ORA_X_IND = 0x01,
	ORA_ZP = 0x05,
	ASL_ZP = 0x06,
	PHP = 0x08,
	ORA_IMM = 0x09,
	ASL_A = 0x0A,
	ORA_ABS = 0x0D,
	ASL_ABS = 0x0E,
	BPL_REL = 0x10,
	ORA_IND_Y = 0x11,
	ORA_ZP_X = 0x15,
	ASL_ZP_X = 0x16,
	CLC = 0x18,
	ORA_ABS_Y = 0x19,
	ORA_ABS_X = 0x1D,
	ASL_ABS_X = 0x1E,
	JSR_ABS = 0x20,
	AND_X_IND = 0x21,
	BIT_ZP = 0x24,
	AND_ZP = 0x25,
	ROL_ZP = 0x26,
	PLP = 0x28,
	AND_IMM = 0x29,
	ROL_A = 0x2A,
	BIT_ABS = 0x2C,
	AND_ABS = 0x2D,
	ROL_ABS = 0x2E,
	BMI_REL = 0x30,
	AND_IND_Y = 0x31,
	AND_ZP_X = 0x35,
	ROL_ZP_X = 0x36,
	SEC = 0x38,
	AND_ABS_Y = 0x39,
	AND_ABS_X = 0x3D,
	ROL_ABS_X = 0x3E,
	RTI_IMP = 0x40,
	EOR_X_IND = 0x41,
	EOR_ZP = 0x45,
	LSR_ZP = 0x46,
	PHA_IMP = 0x48,
	EOR_IMM = 0x49,
	LSR_A = 0x4A,
	JMP_ABS = 0x4C,
	EOR_ABS = 0x4D,
	LSR_ABS = 0x4E,
	BVC_REL = 0x50,
	EOR_IND_Y = 0x51,
	EOR_ZP_X = 0x55,
	LSR_ZP_X = 0x56,
	CLI = 0x58,
	EOR_ABS_Y = 0x59,
	EOR_ABS_X = 0x5D,
	LSR_ABS_X = 0x5E,
	RTS_IMP = 0x60,
	ADC_X_IND = 0x61,
	ADC_ZP = 0x65,
	ROR_ZP = 0x66,
	PLA_IMP = 0x68,
	ADC_IMM = 0x69,
	ROR_A = 0x6A,
	JMP_IND = 0x6C,
	ADC_ABS = 0x6D,
	ROR_ABS = 0x6E,
	BVS_REL = 0x70,
	ADC_IND_Y = 0x71,
	ADC_ZP_X = 0x75,
	ROR_ZP_X = 0x76,
	SEI = 0x78,
	ADC_ABS_Y = 0x79,
	ADC_ABS_X = 0x7D,
	ROR_ABS_X = 0x7E,
	STA_X_IND = 0x81,
	STY_ZP = 0x84,
	STA_ZP = 0x85,
	STX_ZP = 0x86,
	DEY_IMP = 0x88,
	TXA_IMP = 0x8A,
	STY_ABS = 0x8C,
	STA_ABS = 0x8D,
	STX_ABS = 0x8E,
	BCC_REL = 0x90,
	STA_IND_Y = 0x91,
	STY_ZP_X = 0x94,
	STA_ZP_X = 0x95,
	STX_ZP_Y = 0x96,
	TYA_IMP = 0x98,
	STA_ABS_Y = 0x99,
	TXS_IMP = 0x9A,
	STA_ABS_X = 0x9D,
	LDY_IMM = 0xA0,
	LDA_X_IND = 0xA1,
	LDY_ZP = 0xA4,
	LDA_ZP = 0xA5,
	LDX_ZP = 0xA6,
	TAY_IMP = 0xA8,
	LDA_IMM = 0xA9,
	TAX_IMP = 0xAA,
	LDY_ABS = 0xAC,
	LDA_ABS = 0xAD,
	LDX_ABS = 0xAE,
	BCS_REL = 0xB0,
	LDA_IND_Y = 0xB1,
	LDY_ZP_X = 0xB4,
	LDA_ZP_X = 0xB5,
	LDX_ZP_Y = 0xB6,
	CLV_IMP = 0xB8,
	LDA_ABS_Y = 0xB9,
	TSX_IMP = 0xBA,
	LDY_ABS_X = 0xBC,
	LDA_ABS_X = 0xBD,
	LDX_ABS_Y = 0xBE,
	CPY_IMM = 0xC0,
	CMP_X_IND = 0xC1,
	CPY_ZP = 0xC4,
	CMP_ZP = 0xC5,
	DEC_ZP = 0xC6,
	INY_IMP = 0xC8,
	CMP_IMM = 0xC9,
	DEX_IMP = 0xCA,
	CMP_ABS = 0xCD,
	DEC_ABS = 0xCE,
	BNE_REL = 0xD0,
	CMP_IND_Y = 0xD1,
	CMP_ZP_X = 0xD5,
	DEC_ZP_X = 0xD6,
	CLD_IMP = 0xD8,
	CMP_ABS_Y = 0xD9,
	CMP_ABS_X = 0xDD,
	DEC_ABS_X = 0xDE,
	CPX_IMM = 0xE0,
	SBC_X_IND = 0xE1,
	CPX_ZP = 0xE4,
	SBC_ZP = 0xE5,
	INC_ZP = 0xE6,
	INX_IMP = 0xE8,
	SBC_IMM = 0xE9,
	NOP_IMP = 0xEA,
	CPX_ABS = 0xEC,
	SBC_ABS = 0xED,
	INC_ABS = 0xEE,
	BEQ_REL = 0xF0,
	SBC_IND_Y = 0xF1,
	SBC_ZP_X = 0xF5,
	INC_ZP_X = 0xF6,
	SED_IMP = 0xF8,
	SBC_ABS_Y = 0xF9,
	SBC_ABS_X = 0xFD,
	INC_ABS_X = 0xFE,
};
class OpcodeParser {
	public:
		static Opcodes parse(Byte data) {
			switch (data) {
				case (Byte) Opcodes::BRK:
				case (Byte) Opcodes::ORA_X_IND:
				case (Byte) Opcodes::ORA_ZP:
				case (Byte) Opcodes::ASL_ZP:
				case (Byte) Opcodes::PHP:
				case (Byte) Opcodes::ORA_IMM:
				case (Byte) Opcodes::ASL_A:
				case (Byte) Opcodes::ORA_ABS:
				case (Byte) Opcodes::ASL_ABS:
				case (Byte) Opcodes::BPL_REL:
				case (Byte) Opcodes::ORA_IND_Y:
				case (Byte) Opcodes::ORA_ZP_X:
				case (Byte) Opcodes::ASL_ZP_X:
				case (Byte) Opcodes::CLC:
				case (Byte) Opcodes::ORA_ABS_Y:
				case (Byte) Opcodes::ORA_ABS_X:
				case (Byte) Opcodes::ASL_ABS_X:
				case (Byte) Opcodes::JSR_ABS:
				case (Byte) Opcodes::AND_X_IND:
				case (Byte) Opcodes::BIT_ZP:
				case (Byte) Opcodes::AND_ZP:
				case (Byte) Opcodes::ROL_ZP:
				case (Byte) Opcodes::PLP:
				case (Byte) Opcodes::AND_IMM:
				case (Byte) Opcodes::ROL_A:
				case (Byte) Opcodes::BIT_ABS:
				case (Byte) Opcodes::AND_ABS:
				case (Byte) Opcodes::ROL_ABS:
				case (Byte) Opcodes::BMI_REL:
				case (Byte) Opcodes::AND_IND_Y:
				case (Byte) Opcodes::AND_ZP_X:
				case (Byte) Opcodes::ROL_ZP_X:
				case (Byte) Opcodes::SEC:
				case (Byte) Opcodes::AND_ABS_Y:
				case (Byte) Opcodes::AND_ABS_X:
				case (Byte) Opcodes::ROL_ABS_X:
				case (Byte) Opcodes::RTI_IMP:
				case (Byte) Opcodes::EOR_X_IND:
				case (Byte) Opcodes::EOR_ZP:
				case (Byte) Opcodes::LSR_ZP:
				case (Byte) Opcodes::PHA_IMP:
				case (Byte) Opcodes::EOR_IMM:
				case (Byte) Opcodes::LSR_A:
				case (Byte) Opcodes::JMP_ABS:
				case (Byte) Opcodes::EOR_ABS:
				case (Byte) Opcodes::LSR_ABS:
				case (Byte) Opcodes::BVC_REL:
				case (Byte) Opcodes::EOR_IND_Y:
				case (Byte) Opcodes::EOR_ZP_X:
				case (Byte) Opcodes::LSR_ZP_X:
				case (Byte) Opcodes::CLI:
				case (Byte) Opcodes::EOR_ABS_Y:
				case (Byte) Opcodes::EOR_ABS_X:
				case (Byte) Opcodes::LSR_ABS_X:
				case (Byte) Opcodes::RTS_IMP:
				case (Byte) Opcodes::ADC_X_IND:
				case (Byte) Opcodes::ADC_ZP:
				case (Byte) Opcodes::ROR_ZP:
				case (Byte) Opcodes::PLA_IMP:
				case (Byte) Opcodes::ADC_IMM:
				case (Byte) Opcodes::ROR_A:
				case (Byte) Opcodes::JMP_IND:
				case (Byte) Opcodes::ADC_ABS:
				case (Byte) Opcodes::ROR_ABS:
				case (Byte) Opcodes::BVS_REL:
				case (Byte) Opcodes::ADC_IND_Y:
				case (Byte) Opcodes::ADC_ZP_X:
				case (Byte) Opcodes::ROR_ZP_X:
				case (Byte) Opcodes::SEI:
				case (Byte) Opcodes::ADC_ABS_Y:
				case (Byte) Opcodes::ADC_ABS_X:
				case (Byte) Opcodes::ROR_ABS_X:
				case (Byte) Opcodes::STA_X_IND:
				case (Byte) Opcodes::STY_ZP:
				case (Byte) Opcodes::STA_ZP:
				case (Byte) Opcodes::STX_ZP:
				case (Byte) Opcodes::DEY_IMP:
				case (Byte) Opcodes::TXA_IMP:
				case (Byte) Opcodes::STY_ABS:
				case (Byte) Opcodes::STA_ABS:
				case (Byte) Opcodes::STX_ABS:
				case (Byte) Opcodes::BCC_REL:
				case (Byte) Opcodes::STA_IND_Y:
				case (Byte) Opcodes::STY_ZP_X:
				case (Byte) Opcodes::STA_ZP_X:
				case (Byte) Opcodes::STX_ZP_Y:
				case (Byte) Opcodes::TYA_IMP:
				case (Byte) Opcodes::STA_ABS_Y:
				case (Byte) Opcodes::TXS_IMP:
				case (Byte) Opcodes::STA_ABS_X:
				case (Byte) Opcodes::LDY_IMM:
				case (Byte) Opcodes::LDA_X_IND:
				case (Byte) Opcodes::LDY_ZP:
				case (Byte) Opcodes::LDA_ZP:
				case (Byte) Opcodes::LDX_ZP:
				case (Byte) Opcodes::TAY_IMP:
				case (Byte) Opcodes::LDA_IMM:
				case (Byte) Opcodes::TAX_IMP:
				case (Byte) Opcodes::LDY_ABS:
				case (Byte) Opcodes::LDA_ABS:
				case (Byte) Opcodes::LDX_ABS:
				case (Byte) Opcodes::BCS_REL:
				case (Byte) Opcodes::LDA_IND_Y:
				case (Byte) Opcodes::LDY_ZP_X:
				case (Byte) Opcodes::LDA_ZP_X:
				case (Byte) Opcodes::LDX_ZP_Y:
				case (Byte) Opcodes::CLV_IMP:
				case (Byte) Opcodes::LDA_ABS_Y:
				case (Byte) Opcodes::TSX_IMP:
				case (Byte) Opcodes::LDY_ABS_X:
				case (Byte) Opcodes::LDA_ABS_X:
				case (Byte) Opcodes::LDX_ABS_Y:
				case (Byte) Opcodes::CPY_IMM:
				case (Byte) Opcodes::CMP_X_IND:
				case (Byte) Opcodes::CPY_ZP:
				case (Byte) Opcodes::CMP_ZP:
				case (Byte) Opcodes::DEC_ZP:
				case (Byte) Opcodes::INY_IMP:
				case (Byte) Opcodes::CMP_IMM:
				case (Byte) Opcodes::DEX_IMP:
				case (Byte) Opcodes::CMP_ABS:
				case (Byte) Opcodes::DEC_ABS:
				case (Byte) Opcodes::BNE_REL:
				case (Byte) Opcodes::CMP_IND_Y:
				case (Byte) Opcodes::CMP_ZP_X:
				case (Byte) Opcodes::DEC_ZP_X:
				case (Byte) Opcodes::CLD_IMP:
				case (Byte) Opcodes::CMP_ABS_Y:
				case (Byte) Opcodes::CMP_ABS_X:
				case (Byte) Opcodes::DEC_ABS_X:
				case (Byte) Opcodes::CPX_IMM:
				case (Byte) Opcodes::SBC_X_IND:
				case (Byte) Opcodes::CPX_ZP:
				case (Byte) Opcodes::SBC_ZP:
				case (Byte) Opcodes::INC_ZP:
				case (Byte) Opcodes::INX_IMP:
				case (Byte) Opcodes::SBC_IMM:
				case (Byte) Opcodes::NOP_IMP:
				case (Byte) Opcodes::CPX_ABS:
				case (Byte) Opcodes::SBC_ABS:
				case (Byte) Opcodes::INC_ABS:
				case (Byte) Opcodes::BEQ_REL:
				case (Byte) Opcodes::SBC_IND_Y:
				case (Byte) Opcodes::SBC_ZP_X:
				case (Byte) Opcodes::INC_ZP_X:
				case (Byte) Opcodes::SED_IMP:
				case (Byte) Opcodes::SBC_ABS_Y:
				case (Byte) Opcodes::SBC_ABS_X:
				case (Byte) Opcodes::INC_ABS_X:
					return (Opcodes)data;
				default:
					return Opcodes::NOP_IMP;
				}
		}
};

#endif